services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: udaykirandasari/assignment3_backend:latest
    container_name: backend-container
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./secrets:/app/secrets
      - ./env:/app/.env

    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: udaykirandasari/assignment3_frontend:latest
    container_name: frontend-container
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    depends_on:
      - backend
    volumes:
      - ./secrets:/app/secrets
      - ./env:/app/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: